language: ruby
rvm:
  - 2.3.0
services:
  - postgresql
env:
  # - TEST_DIRECTORY=spec/models
  # - TEST_DIRECTORY=spec/features
  - TEST_DIRECTORY=spec
before_script:
  - psql -c 'create database air_bnb_clone_test;' -U postgres
script:
  - xvfb-run bundle exec rspec $TEST_DIRECTORY
cache: bundler
sudo: false
secure: "ZcHsKRLUpfZCfKRSNYC5LaaSh18sq5Ew5Koy1K3tuD9bv08EA/D4TByNOagNkuiDCoq9DekPHhKv16ShQZAZh5wG7/fK4Xvv/eS4Idgf8IHIcvxAfwpRbU+9tMn7CykNfMMc4xaMS3KGF08A8OvK1GeiiP2DzK7gFFz0n9cyZGD/JApZzA/URSTIL0WqDLwZXVZUoYmBxsATj94gUbWDTrgZCMaR2xHEYCEuiknnN8dMw9DdgYZZipAefqzCBg2x1tzjX/VcSwO4J7EnOfXBi0Io9fPseiQStv7HNz7CI0b5z7YAvHlzO5gV6zFAZQZmkbPxkiaXA1Ri3+Ei15kqQTYBgo+Z7lRn9W2iMvLvvRVN7Gx5RneZZ/1H1TI1y7HC3cQ9IWghyAzazIr9AqQLfpc6OKVmhEfIq3JCeoVT3ph00GEeDg8JuTz/9jklTpnO0N0f4aE0pgejzguWZ/W3xFZNFTgrQiIYZlRevNdhMx/jg1iitCjITiE1j+pb0nsERueOUrXbJ90pGytVzGW0wPZxZSF4CpfHoTkpVmLoeGPQpHtEMSTZeBzkUHk//+g52mMnLpDfjswmVaNPiaHYcXuckN/rgku/lOIwnctOT42kGUCdN+pmQhSvFCmnM13w439vvq9pK6+lRLwSbbs3W39wjsWaRN6rxx7ZX4gm7cQ="
